# docker-compose.yml
version: '3.5'

services:
  puppeteer:
    container_name: futebolcrawler_puppeteer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    working_dir: /src
    command: tail -F anything
